Lidar_front_end:
   lidar_type: 4   # 1 for Livox-avia, 3 for Ouster-OS1-64, 4 for RS-Bpearl
   N_SCANS: 32 # WF: 6 for Livox Horizon
   using_raw_point: 1
   point_step: 1 # TODO: Check its role, can affect scanning process
#   point_filter_num: 4
   blind: 2

   # TODO: There is no fov_degree and det_range as for FAST-LIO. Check the code to change in case they exist
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1]
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600] TODO: Check its role
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1280
   image_height: 720
   camera_intrinsic:
     [ 513.9195221, 0.0, 638.20818345,
       0.0, 514.26664969, 368.26763722,
       0.0, 0.0, 1.0 ]
   camera_dist_coeffs: [-0.01318935, -0.00131136, -0.00091831, -0.00087753, 0.0]  #k1, k2, p1, p2, k3
   camera_ext_R: # Camera->IMU (IMU is a base frame) TODO
      [ 0.99663, 0.07122, -0.04059,
      -0.06879, 0.99592, 0.05840,
      0.04459, -0.05541, 0.99747 ]
   camera_ext_t: [ -0.00997, -0.16352, -0.04475]
   
r3live_lio:
   #   <param name="r3live_lio/lio_update_point_step" type="int" value="6" />
   lio_update_point_step: 6   # Point step used for LIO update.  TODO: Check. Can affect scanning !!!
   max_iteration: 3           # Maximum times of LIO esikf. TODO: Check. Can affect scanning
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   # TODO: Check. Can affect scanning (!!!) We changed for surface, why not change for corners?
   filter_size_surf: 0.50
   filter_size_surf_z: 0.50
   filter_size_map: 0.50
   lidar_ext_R: # LiDAR->IMU (IMU is a base frame)
     [ 0.99663, 0.07122, -0.04059,
       -0.06879, 0.99592, 0.05840,
       0.04459, -0.05541, 0.99747 ]
   lidar_ext_t: [ -0.00997, -0.16352, -0.04475]
