Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6 # WF: 6 for Livox Horizon
   using_raw_point: 1
   point_step: 1 # TODO: Check its role, can affect scanning process
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1]
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1]
   maximum_vio_tracked_pts: 1500     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1280
   image_height: 720
   camera_intrinsic:
     [ 513.9195221, 0.0, 638.20818345,
       0.0, 514.26664969, 368.26763722,
       0.0, 0.0, 1.0 ]
   camera_dist_coeffs: [-0.01318935, -0.00131136, -0.00091831, -0.00087753, 0.0]  #k1, k2, p1, p2, k3
   camera_ext_R: # Camera->IMU (IMU is a base frame) TODO
      [ 0.01669659, 0.02366404, 0.99958053,
        -0.99980313, -0.01032411, 0.01694472,
        0.01072076, -0.99966666, 0.023487 ]
   camera_ext_t: [ -0.13722137, -0.01880091, 0.00905537 ]
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  TODO: Check. Can affect scanning
   max_iteration: 2           # Maximum times of LIO esikf. TODO: Check. Can affect scanning
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   # TODO: Check. Can affect scanning
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30
   lidar_ext_R: # LiDAR->IMU (IMU is a base frame)
      [ 0.99479, -0.01504, -0.10087,
        0.01701, 0.99968, 0.01876,
        0.10056, -0.02038, 0.99472 ]
   lidar_ext_t: [ -0.13211, -0.11712, -0.06379 ]
   acc_noise: 0.04641977329563476
   gyro_noise: 0.013213877349668923
   acc_random_walk: 0.0019703618139556927
   gyro_random_walk: 2.206282069791498e-05