Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6 # WF: 6 for Livox Horizon
   using_raw_point: 1
   point_step: 1 # TODO: Check its role, can affect scanning process
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1920
   image_height: 1080
   camera_intrinsic:
     [ 1005.2349658444527, 0.0, 951.1921864937732,
       0.0, 1005.5618437833184, 562.7644996499605,
       0.0, 0.0, 1.0 ]
   camera_dist_coeffs: [0.05100155355585925, -0.04377006383686457, 0.000625333133609035, 0.0024466916033656257, 0.0]  #k1, k2, p1, p2, k3
   camera_ext_R:
      [-0.00068, 0.07716, 0.99702,
        0.99995, -0.00969, 0.00143,
        0.00977, 0.99697, -0.07715]
   camera_ext_t: [-0.01034, -0.05583, -0.16189]
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  TODO: Check. Can affect scanning
   max_iteration: 2           # Maximum times of LIO esikf. TODO: Check. Can affect scanning
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   # TODO: Check. Can affect scanning
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30